#%RAML 1.0
title: sys-mc-tdx-api
# The version starts from 0.1 and gradually progresses as the API Definition is updated.
version: 1.1

/tdx:
  post:
 
   
/tdxfiles:
  post:


/tdxfiles-status:
  post:
